package com.mycompany.proyectofisica;

import javax.swing.JOptionPane;

/**
 *
 * @author gomez
 */
public class Aceleracion extends javax.swing.JFrame {

    /**
     * Creates new form Aceleracion
     */
    public Aceleracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        CalcularAceleracion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TiempoLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tiempoField = new javax.swing.JTextField();
        unidadTiempo = new javax.swing.JComboBox<>();
        AceleracionLabel = new javax.swing.JLabel();
        VelocidadFinalField = new javax.swing.JTextField();
        Respuesta = new javax.swing.JLabel();
        VelocidadFinalLabel1 = new javax.swing.JLabel();
        VelocidadInicialField = new javax.swing.JTextField();
        unidadVelocidadFinal = new javax.swing.JComboBox<>();
        unidadSalida = new javax.swing.JComboBox<>();
        unidadVelocidadInicial = new javax.swing.JComboBox<>();
        distanciaLabel = new javax.swing.JLabel();
        distanciaField = new javax.swing.JTextField();
        unidadDistancia = new javax.swing.JComboBox<>();
        formula = new javax.swing.JLabel();
        Limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(241, 191, 217));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(190, 108, 157));
        jLabel1.setText("Formula:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, -1, -1));

        Volver.setBackground(new java.awt.Color(245, 215, 226));
        Volver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Volver.setForeground(new java.awt.Color(209, 129, 148));
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 490, -1, -1));

        CalcularAceleracion.setBackground(new java.awt.Color(241, 191, 217));
        CalcularAceleracion.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        CalcularAceleracion.setForeground(new java.awt.Color(190, 108, 157));
        CalcularAceleracion.setText("calcular");
        CalcularAceleracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularAceleracionActionPerformed(evt);
            }
        });
        getContentPane().add(CalcularAceleracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, 50));

        jLabel6.setBackground(new java.awt.Color(241, 191, 217));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(190, 108, 157));
        jLabel6.setText("Respuesta en:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        TiempoLabel.setBackground(new java.awt.Color(241, 191, 217));
        TiempoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TiempoLabel.setForeground(new java.awt.Color(190, 108, 157));
        TiempoLabel.setText("Tiempo (t):");
        getContentPane().add(TiempoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel5.setBackground(new java.awt.Color(241, 191, 217));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(190, 108, 157));
        jLabel5.setText("Velocidad inicial (v₀):");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel4.setBackground(new java.awt.Color(241, 191, 217));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(190, 108, 157));
        jLabel4.setText("Calcular la aceleracion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        tiempoField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tiempoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoFieldActionPerformed(evt);
            }
        });
        getContentPane().add(tiempoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 260, 30));

        unidadTiempo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadTiempo.setForeground(new java.awt.Color(190, 108, 157));
        unidadTiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "horas", "segundos" }));
        unidadTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadTiempoActionPerformed(evt);
            }
        });
        getContentPane().add(unidadTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 150, 30));

        AceleracionLabel.setBackground(new java.awt.Color(241, 191, 217));
        AceleracionLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AceleracionLabel.setForeground(new java.awt.Color(190, 108, 157));
        AceleracionLabel.setText("Aceleracion (a):");
        getContentPane().add(AceleracionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, -1, -1));

        VelocidadFinalField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        VelocidadFinalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VelocidadFinalFieldActionPerformed(evt);
            }
        });
        getContentPane().add(VelocidadFinalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 290, 30));

        Respuesta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(Respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 130, 330, 40));

        VelocidadFinalLabel1.setBackground(new java.awt.Color(241, 191, 217));
        VelocidadFinalLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        VelocidadFinalLabel1.setForeground(new java.awt.Color(190, 108, 157));
        VelocidadFinalLabel1.setText("Velocidad final (v):");
        getContentPane().add(VelocidadFinalLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        VelocidadInicialField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        VelocidadInicialField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VelocidadInicialFieldActionPerformed(evt);
            }
        });
        getContentPane().add(VelocidadInicialField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 260, 30));

        unidadVelocidadFinal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadVelocidadFinal.setForeground(new java.awt.Color(190, 108, 157));
        unidadVelocidadFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km/h", "m/s" }));
        unidadVelocidadFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadVelocidadFinalActionPerformed(evt);
            }
        });
        getContentPane().add(unidadVelocidadFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 110, 30));

        unidadSalida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadSalida.setForeground(new java.awt.Color(190, 108, 157));
        unidadSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km/h²", "m/s²" }));
        unidadSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(unidadSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 50, 160, 40));

        unidadVelocidadInicial.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadVelocidadInicial.setForeground(new java.awt.Color(190, 108, 157));
        unidadVelocidadInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km/h", "m/s" }));
        unidadVelocidadInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadVelocidadInicialActionPerformed(evt);
            }
        });
        getContentPane().add(unidadVelocidadInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 110, 30));

        distanciaLabel.setBackground(new java.awt.Color(241, 191, 217));
        distanciaLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        distanciaLabel.setForeground(new java.awt.Color(190, 108, 157));
        distanciaLabel.setText("distancia (x):");
        getContentPane().add(distanciaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        distanciaField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        distanciaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanciaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(distanciaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 260, 30));

        unidadDistancia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadDistancia.setForeground(new java.awt.Color(190, 108, 157));
        unidadDistancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km", "mts" }));
        unidadDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadDistanciaActionPerformed(evt);
            }
        });
        getContentPane().add(unidadDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 110, 30));

        formula.setBackground(new java.awt.Color(241, 191, 217));
        formula.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        formula.setForeground(new java.awt.Color(190, 108, 157));
        getContentPane().add(formula, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 510, 140));

        Limpiar.setBackground(new java.awt.Color(245, 215, 226));
        Limpiar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Limpiar.setForeground(new java.awt.Color(209, 129, 148));
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.dispose();
        SeleccionProblemas volver = new SeleccionProblemas();
        volver.setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    private void CalcularAceleracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularAceleracionActionPerformed
       try {
            // Verificar si se ingresó cada campo
            boolean tieneV = !VelocidadFinalField.getText().isEmpty();
            boolean tieneV0 = !VelocidadInicialField.getText().isEmpty();
            boolean tieneT = !tiempoField.getText().isEmpty();
            boolean tieneD = !distanciaField.getText().isEmpty();

            // Parsear valores
            double v = tieneV ? Double.parseDouble(VelocidadFinalField.getText()) : 0;
            double v0 = tieneV0 ? Double.parseDouble(VelocidadInicialField.getText()) : 0;
            double t = tieneT ? Double.parseDouble(tiempoField.getText()) : 0;
            double d = tieneD ? Double.parseDouble(distanciaField.getText()) : 0;

            // Conversión de unidades a estándar
            if (tieneV && unidadVelocidadFinal.getSelectedItem().equals("km/h")) v /= 3.6;
            if (tieneV0 && unidadVelocidadInicial.getSelectedItem().equals("km/h")) v0 /= 3.6;
            if (tieneT && unidadTiempo.getSelectedItem().equals("horas")) t *= 3600;
            if (tieneD && unidadDistancia.getSelectedItem().equals("km")) d *= 1000;

            double a = 0;
            String formulaUsada = "";

            // Caso 1: a = (v - v₀) / t
            if (tieneV && tieneV0 && tieneT && t != 0) {
                a = (v - v0) / t;
                formulaUsada = "a = (v - v₀) / t";
            }
            // Caso 2: a = (v² - v₀²) / (2·d)
            else if (tieneV && tieneV0 && tieneD && d != 0) {
                a = (Math.pow(v, 2) - Math.pow(v0, 2)) / (2 * d);
                formulaUsada = "a = (v² - v₀²) / (2·d)";
            }
            // Caso 3: a = [2·(d - v₀·t)] / t²
            else if (tieneD && tieneV0 && tieneT && t != 0) {
                a = (2 * (d - v0 * t)) / Math.pow(t, 2);
                formulaUsada = "a = 2(d - v₀·t) / t²";
            } else {
                JOptionPane.showMessageDialog(null, "Ingresa al menos 3 variables (excepto aceleración).");
                return;
            }

            // Mostrar en km/h² si el usuario lo pide
            if (unidadSalida.getSelectedItem().equals("km/h²")) {
                a *= 12960;
            }

            // Mostrar resultado
            Respuesta.setText(String.format("%.2f %s", a, unidadSalida.getSelectedItem().toString()));
            formula.setText(formulaUsada);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error: Ingresa solo números válidos.");
        }
    }//GEN-LAST:event_CalcularAceleracionActionPerformed

    private void tiempoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoFieldActionPerformed

    private void unidadTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadTiempoActionPerformed

    private void VelocidadFinalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VelocidadFinalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VelocidadFinalFieldActionPerformed

    private void VelocidadInicialFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VelocidadInicialFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VelocidadInicialFieldActionPerformed

    private void unidadVelocidadFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadVelocidadFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadVelocidadFinalActionPerformed

    private void unidadSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadSalidaActionPerformed

    private void unidadVelocidadInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadVelocidadInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadVelocidadInicialActionPerformed

    private void distanciaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanciaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distanciaFieldActionPerformed

    private void unidadDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadDistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadDistanciaActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // Limpiar todos los campos de texto

        VelocidadInicialField.setText("");
        tiempoField.setText("");
        VelocidadInicialField.setText("");
        distanciaField.setText("");

        // Reiniciar los JComboBox a su primer elemento (opcional)
        unidadVelocidadFinal.setSelectedIndex(0);
        unidadVelocidadInicial.setSelectedIndex(0);
        unidadDistancia.setSelectedIndex(0);
        unidadTiempo.setSelectedIndex(0);

        // Limpiar los resultados y fórmulas mostradas
        Respuesta.setText("");
        formula.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AceleracionLabel;
    private javax.swing.JButton CalcularAceleracion;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel Respuesta;
    private javax.swing.JLabel TiempoLabel;
    private javax.swing.JTextField VelocidadFinalField;
    private javax.swing.JLabel VelocidadFinalLabel1;
    private javax.swing.JTextField VelocidadInicialField;
    private javax.swing.JButton Volver;
    private javax.swing.JTextField distanciaField;
    private javax.swing.JLabel distanciaLabel;
    private javax.swing.JLabel formula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tiempoField;
    private javax.swing.JComboBox<String> unidadDistancia;
    private javax.swing.JComboBox<String> unidadSalida;
    private javax.swing.JComboBox<String> unidadTiempo;
    private javax.swing.JComboBox<String> unidadVelocidadFinal;
    private javax.swing.JComboBox<String> unidadVelocidadInicial;
    // End of variables declaration//GEN-END:variables
}
