package com.mycompany.proyectofisica;

import javax.swing.JOptionPane;

/**
 *
 * @author gomez
 */
public class alturaInicial extends javax.swing.JFrame {

    /**
     * Creates new form alturaInicial
     */
    public alturaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        unidadV0y = new javax.swing.JComboBox<>();
        V0yField = new javax.swing.JTextField();
        AceleracionLabel = new javax.swing.JLabel();
        TiempoLabel = new javax.swing.JLabel();
        alturayField = new javax.swing.JTextField();
        unidadY = new javax.swing.JComboBox<>();
        Limpiar = new javax.swing.JButton();
        CalcularVelocidadInicial = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        formula = new javax.swing.JLabel();
        Respuesta = new javax.swing.JLabel();
        unidadSalida = new javax.swing.JComboBox<>();
        hMaxField = new javax.swing.JTextField();
        unidadhMax = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TtotalField = new javax.swing.JTextField();
        unidadTtotal = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        VelocidadInicialField = new javax.swing.JTextField();
        unidadVelocidadInicial = new javax.swing.JComboBox<>();
        distanciaLabel = new javax.swing.JLabel();
        anguloField = new javax.swing.JTextField();
        unidadAngulo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        tiempoEnUnInstanteField = new javax.swing.JTextField();
        unidadTiempo = new javax.swing.JComboBox<>();
        TiempoLabel1 = new javax.swing.JLabel();
        AlcanceField = new javax.swing.JTextField();
        unidadAlcance = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(241, 191, 217));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(190, 108, 157));
        jLabel4.setText("Calcular altura inicial");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        unidadV0y.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadV0y.setForeground(new java.awt.Color(190, 108, 157));
        unidadV0y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m/s", "km/h" }));
        unidadV0y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadV0yActionPerformed(evt);
            }
        });
        getContentPane().add(unidadV0y, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 100, 30));

        V0yField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        V0yField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V0yFieldActionPerformed(evt);
            }
        });
        getContentPane().add(V0yField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 290, 30));

        AceleracionLabel.setBackground(new java.awt.Color(241, 191, 217));
        AceleracionLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AceleracionLabel.setForeground(new java.awt.Color(190, 108, 157));
        AceleracionLabel.setText("V0y:");
        getContentPane().add(AceleracionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        TiempoLabel.setBackground(new java.awt.Color(241, 191, 217));
        TiempoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TiempoLabel.setForeground(new java.awt.Color(190, 108, 157));
        TiempoLabel.setText("altura especifica (y):");
        getContentPane().add(TiempoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        alturayField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        alturayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturayFieldActionPerformed(evt);
            }
        });
        getContentPane().add(alturayField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 260, 30));

        unidadY.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadY.setForeground(new java.awt.Color(190, 108, 157));
        unidadY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km", "m" }));
        unidadY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadYActionPerformed(evt);
            }
        });
        getContentPane().add(unidadY, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 110, 30));

        Limpiar.setBackground(new java.awt.Color(245, 215, 226));
        Limpiar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Limpiar.setForeground(new java.awt.Color(209, 129, 148));
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, -1, -1));

        CalcularVelocidadInicial.setBackground(new java.awt.Color(241, 191, 217));
        CalcularVelocidadInicial.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        CalcularVelocidadInicial.setForeground(new java.awt.Color(190, 108, 157));
        CalcularVelocidadInicial.setText("calcular");
        CalcularVelocidadInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularVelocidadInicialActionPerformed(evt);
            }
        });
        getContentPane().add(CalcularVelocidadInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, -1, 50));

        Volver.setBackground(new java.awt.Color(245, 215, 226));
        Volver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Volver.setForeground(new java.awt.Color(209, 129, 148));
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 590, -1, -1));

        jLabel1.setBackground(new java.awt.Color(241, 191, 217));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(190, 108, 157));
        jLabel1.setText("Formula:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, -1, -1));

        jLabel5.setBackground(new java.awt.Color(241, 191, 217));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(190, 108, 157));
        jLabel5.setText("Altura inicial:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, -1, -1));

        jLabel6.setBackground(new java.awt.Color(241, 191, 217));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(190, 108, 157));
        jLabel6.setText("Respuesta en:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        formula.setBackground(new java.awt.Color(241, 191, 217));
        formula.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        formula.setForeground(new java.awt.Color(190, 108, 157));
        getContentPane().add(formula, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 630, 140));

        Respuesta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(Respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, 330, 40));

        unidadSalida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadSalida.setForeground(new java.awt.Color(190, 108, 157));
        unidadSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m", "km" }));
        unidadSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(unidadSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 30, 130, 50));

        hMaxField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hMaxField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hMaxFieldActionPerformed(evt);
            }
        });
        getContentPane().add(hMaxField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 260, 30));

        unidadhMax.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadhMax.setForeground(new java.awt.Color(190, 108, 157));
        unidadhMax.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m", "km" }));
        unidadhMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadhMaxActionPerformed(evt);
            }
        });
        getContentPane().add(unidadhMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 80, 30));

        jLabel12.setBackground(new java.awt.Color(241, 191, 217));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(190, 108, 157));
        jLabel12.setText("Altura maxima (hmax):");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 40));

        jLabel9.setBackground(new java.awt.Color(241, 191, 217));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(190, 108, 157));
        jLabel9.setText("Ttotal:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 40));

        TtotalField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TtotalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtotalFieldActionPerformed(evt);
            }
        });
        getContentPane().add(TtotalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 260, 30));

        unidadTtotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadTtotal.setForeground(new java.awt.Color(190, 108, 157));
        unidadTtotal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "horas", "minutos", "segundos" }));
        unidadTtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadTtotalActionPerformed(evt);
            }
        });
        getContentPane().add(unidadTtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 150, 30));

        jLabel7.setBackground(new java.awt.Color(241, 191, 217));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(190, 108, 157));
        jLabel7.setText("Velocidad inicial (v₀):");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        VelocidadInicialField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        VelocidadInicialField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VelocidadInicialFieldActionPerformed(evt);
            }
        });
        getContentPane().add(VelocidadInicialField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 260, 30));

        unidadVelocidadInicial.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadVelocidadInicial.setForeground(new java.awt.Color(190, 108, 157));
        unidadVelocidadInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m/s", "km/h" }));
        unidadVelocidadInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadVelocidadInicialActionPerformed(evt);
            }
        });
        getContentPane().add(unidadVelocidadInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 110, 30));

        distanciaLabel.setBackground(new java.awt.Color(241, 191, 217));
        distanciaLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        distanciaLabel.setForeground(new java.awt.Color(190, 108, 157));
        distanciaLabel.setText("Angulo (θ):");
        getContentPane().add(distanciaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        anguloField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        anguloField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anguloFieldActionPerformed(evt);
            }
        });
        getContentPane().add(anguloField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 260, 30));

        unidadAngulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadAngulo.setForeground(new java.awt.Color(190, 108, 157));
        unidadAngulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°", "rad" }));
        unidadAngulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadAnguloActionPerformed(evt);
            }
        });
        getContentPane().add(unidadAngulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 90, 30));

        jLabel8.setBackground(new java.awt.Color(241, 191, 217));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(190, 108, 157));
        jLabel8.setText("Tiempo en un instante (t'):");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 40));

        tiempoEnUnInstanteField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tiempoEnUnInstanteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoEnUnInstanteFieldActionPerformed(evt);
            }
        });
        getContentPane().add(tiempoEnUnInstanteField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 260, 30));

        unidadTiempo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadTiempo.setForeground(new java.awt.Color(190, 108, 157));
        unidadTiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "horas", "minutos", "segundos" }));
        unidadTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadTiempoActionPerformed(evt);
            }
        });
        getContentPane().add(unidadTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 150, 30));

        TiempoLabel1.setBackground(new java.awt.Color(241, 191, 217));
        TiempoLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TiempoLabel1.setForeground(new java.awt.Color(190, 108, 157));
        TiempoLabel1.setText("Alcance (R):");
        getContentPane().add(TiempoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        AlcanceField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AlcanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlcanceFieldActionPerformed(evt);
            }
        });
        getContentPane().add(AlcanceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 260, 30));

        unidadAlcance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadAlcance.setForeground(new java.awt.Color(190, 108, 157));
        unidadAlcance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m", "km" }));
        unidadAlcance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadAlcanceActionPerformed(evt);
            }
        });
        getContentPane().add(unidadAlcance, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unidadV0yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadV0yActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadV0yActionPerformed

    private void V0yFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V0yFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_V0yFieldActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        V0yField.setText("");
        alturayField.setText("");
        VelocidadInicialField.setText("");
        anguloField.setText("");
        hMaxField.setText("");
        tiempoEnUnInstanteField.setText("");
        TtotalField.setText("");
        Respuesta.setText("");
        formula.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void CalcularVelocidadInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularVelocidadInicialActionPerformed
        try {
            double hMax = hMaxField.getText().isEmpty() ? 0 : Double.parseDouble(hMaxField.getText());
            double V0 = VelocidadInicialField.getText().isEmpty() ? 0 : Double.parseDouble(VelocidadInicialField.getText());
            double angulo = anguloField.getText().isEmpty() ? 0 : Double.parseDouble(anguloField.getText());
            double V0y = V0yField.getText().isEmpty() ? 0 : Double.parseDouble(V0yField.getText());
            double hEspecifica = alturayField.getText().isEmpty() ? 0 : Double.parseDouble(alturayField.getText());
            double tiempoEspecifico = tiempoEnUnInstanteField.getText().isEmpty() ? 0 : Double.parseDouble(tiempoEnUnInstanteField.getText());
            double tiempoTotal = TtotalField.getText().isEmpty() ? 0 : Double.parseDouble(TtotalField.getText());
            double alcance = AlcanceField.getText().isEmpty() ? 0 : Double.parseDouble(AlcanceField.getText());

            // Unidades
            if (unidadVelocidadInicial.getSelectedItem().equals("km/h")) {
                V0 /= 3.6;
            }
            if (unidadV0y.getSelectedItem().equals("km/h")) {
                V0y /= 3.6;
            }
            if (unidadTiempo.getSelectedItem().equals("minutos")) {
                tiempoEspecifico *= 60;
            }
            if (unidadTiempo.getSelectedItem().equals("horas")) {
                tiempoEspecifico *= 3600;
            }
            if (unidadTtotal.getSelectedItem().equals("minutos")) {
                tiempoTotal *= 60;
            }
            if (unidadTtotal.getSelectedItem().equals("horas")) {
                tiempoTotal *= 3600;
            }
            if (unidadhMax.getSelectedItem().equals("km")) {
                hMax *= 1000;
            }
            if (unidadY.getSelectedItem().equals("km")) {
                hEspecifica *= 1000;
            }
            if (unidadAlcance.getSelectedItem().equals("km")) {
                alcance *= 1000;
            }

            double g = 9.81;
            double y0 = 0;
            String formulaUsada = "";

            // Convertir ángulo
            double anguloRad = Math.toRadians(angulo);

            // Calcular V0y si no está y hay V0 y ángulo
            if (V0y == 0 && V0 != 0 && angulo != 0) {
                V0y = V0 * Math.sin(anguloRad);
            }

            // Calcular V0y si hay alcance, tiempo y ángulo
            if (V0y == 0 && alcance != 0 && tiempoTotal != 0 && angulo != 0) {
                double V0x = alcance / tiempoTotal;
                V0 = V0x / Math.cos(anguloRad);
                V0y = V0 * Math.sin(anguloRad);
            }

            // Combinaciones posibles
            if (hMax != 0 && V0y != 0) {
                y0 = hMax - (Math.pow(V0y, 2) / (2 * g));
                formulaUsada = "y₀ = hₘₐₓ - (V₀y² / 2g)";
            } else if (hEspecifica != 0 && tiempoEspecifico != 0 && V0y != 0) {
                y0 = hEspecifica - (V0y * tiempoEspecifico - 0.5 * g * Math.pow(tiempoEspecifico, 2));
                formulaUsada = "y₀ = h(t) - (V₀y·t - ½·g·t²)";
            } else if (tiempoTotal != 0 && V0y != 0) {
                y0 = V0y * tiempoTotal - 0.5 * g * Math.pow(tiempoTotal, 2);
                formulaUsada = "y₀ = V₀y·tₜₒₜ - ½·g·tₜₒₜ²";
            } else if (V0 != 0 && angulo != 0 && alcance != 0) {
                double T = alcance / (V0 * Math.cos(anguloRad));
                double h = (V0 * Math.sin(anguloRad)) * T - 0.5 * g * Math.pow(T, 2);
                y0 = h + 0.5 * g * Math.pow(T, 2);
                formulaUsada = "y₀ = h + ½·g·T²";
            } else if (hMax != 0 && tiempoTotal != 0) {
                double tMitad = tiempoTotal / 2;
                y0 = hMax - 0.5 * g * Math.pow(tMitad, 2);
                formulaUsada = "y₀ = hₘₐₓ - ½·g·(tₜₒₜ / 2)²";
            } else if (V0 != 0 && angulo != 0 && tiempoTotal != 0) {
                double Vy = V0 * Math.sin(anguloRad);
                y0 = Vy * tiempoTotal - 0.5 * g * Math.pow(tiempoTotal, 2);
                formulaUsada = "y₀ = V₀·sen(θ)·t - ½·g·t²";
            } else if (V0 != 0 && angulo != 0 && hEspecifica != 0 && tiempoEspecifico != 0) {
                double Vy = V0 * Math.sin(anguloRad);
                y0 = hEspecifica - (Vy * tiempoEspecifico - 0.5 * g * Math.pow(tiempoEspecifico, 2));
                formulaUsada = "y₀ = h(t) - (V₀·sen(θ)·t - ½·g·t²)";
            } else {
                JOptionPane.showMessageDialog(this, "⚠️ Ingresa una combinación válida de datos.");
                return;
            }
            if (unidadSalida.getSelectedItem().equals("km")) {
                y0 /= 1000;
            }

            // Mostrar resultado
            Respuesta.setText(String.format("%.2f", y0));
            formula.setText(formulaUsada);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "❌ Error: Ingresa solo números válidos.");
        }
    }//GEN-LAST:event_CalcularVelocidadInicialActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.dispose();
        SeleccionProblemas volver = new SeleccionProblemas();
        volver.setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    private void hMaxFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hMaxFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hMaxFieldActionPerformed

    private void unidadhMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadhMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadhMaxActionPerformed

    private void TtotalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtotalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TtotalFieldActionPerformed

    private void unidadTtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadTtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadTtotalActionPerformed

    private void VelocidadInicialFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VelocidadInicialFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VelocidadInicialFieldActionPerformed

    private void unidadVelocidadInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadVelocidadInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadVelocidadInicialActionPerformed

    private void unidadSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadSalidaActionPerformed

    }//GEN-LAST:event_unidadSalidaActionPerformed

    private void unidadYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadYActionPerformed

    private void alturayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturayFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturayFieldActionPerformed

    private void anguloFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anguloFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anguloFieldActionPerformed

    private void unidadAnguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadAnguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadAnguloActionPerformed

    private void tiempoEnUnInstanteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoEnUnInstanteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoEnUnInstanteFieldActionPerformed

    private void unidadTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadTiempoActionPerformed

    private void AlcanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlcanceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlcanceFieldActionPerformed

    private void unidadAlcanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadAlcanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadAlcanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AceleracionLabel;
    private javax.swing.JTextField AlcanceField;
    private javax.swing.JButton CalcularVelocidadInicial;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel Respuesta;
    private javax.swing.JLabel TiempoLabel;
    private javax.swing.JLabel TiempoLabel1;
    private javax.swing.JTextField TtotalField;
    private javax.swing.JTextField V0yField;
    private javax.swing.JTextField VelocidadInicialField;
    private javax.swing.JButton Volver;
    private javax.swing.JTextField alturayField;
    private javax.swing.JTextField anguloField;
    private javax.swing.JLabel distanciaLabel;
    private javax.swing.JLabel formula;
    private javax.swing.JTextField hMaxField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tiempoEnUnInstanteField;
    private javax.swing.JComboBox<String> unidadAlcance;
    private javax.swing.JComboBox<String> unidadAngulo;
    private javax.swing.JComboBox<String> unidadSalida;
    private javax.swing.JComboBox<String> unidadTiempo;
    private javax.swing.JComboBox<String> unidadTtotal;
    private javax.swing.JComboBox<String> unidadV0y;
    private javax.swing.JComboBox<String> unidadVelocidadInicial;
    private javax.swing.JComboBox<String> unidadY;
    private javax.swing.JComboBox<String> unidadhMax;
    // End of variables declaration//GEN-END:variables
}
