/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofisica;

import javax.swing.JOptionPane;

/**
 *
 * @author gomez
 */
public class DistanciaMRUV extends javax.swing.JFrame {

    /**
     * Creates new form DistanciaMRUV
     */
    public DistanciaMRUV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        CalcularAceleracion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TiempoLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AceleracionField = new javax.swing.JTextField();
        unidadSalida = new javax.swing.JComboBox<>();
        AceleracionLabel = new javax.swing.JLabel();
        VelocidadFinalField = new javax.swing.JTextField();
        Respuesta = new javax.swing.JLabel();
        VelocidadFinalLabel1 = new javax.swing.JLabel();
        VelocidadInicialField = new javax.swing.JTextField();
        unidadVelocidadFinal = new javax.swing.JComboBox<>();
        unidadAceleracion = new javax.swing.JComboBox<>();
        unidadVelocidadInicial = new javax.swing.JComboBox<>();
        TiempoLabel1 = new javax.swing.JLabel();
        tiempoField = new javax.swing.JTextField();
        unidadTiempo = new javax.swing.JComboBox<>();
        formula = new javax.swing.JLabel();
        Limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(241, 191, 217));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(190, 108, 157));
        jLabel1.setText("Formula:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, -1, -1));

        Volver.setBackground(new java.awt.Color(245, 215, 226));
        Volver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Volver.setForeground(new java.awt.Color(209, 129, 148));
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 570, -1, -1));

        CalcularAceleracion.setBackground(new java.awt.Color(241, 191, 217));
        CalcularAceleracion.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        CalcularAceleracion.setForeground(new java.awt.Color(190, 108, 157));
        CalcularAceleracion.setText("calcular");
        CalcularAceleracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularAceleracionActionPerformed(evt);
            }
        });
        getContentPane().add(CalcularAceleracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, 50));

        jLabel6.setBackground(new java.awt.Color(241, 191, 217));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(190, 108, 157));
        jLabel6.setText("Respuesta en:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, -1, -1));

        TiempoLabel.setBackground(new java.awt.Color(241, 191, 217));
        TiempoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TiempoLabel.setForeground(new java.awt.Color(190, 108, 157));
        TiempoLabel.setText("Distancia (d):");
        getContentPane().add(TiempoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, -1, -1));

        jLabel5.setBackground(new java.awt.Color(241, 191, 217));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(190, 108, 157));
        jLabel5.setText("Velocidad inicial (v₀):");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        AceleracionField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AceleracionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceleracionFieldActionPerformed(evt);
            }
        });
        getContentPane().add(AceleracionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 260, 30));

        unidadSalida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadSalida.setForeground(new java.awt.Color(190, 108, 157));
        unidadSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m", "km" }));
        unidadSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(unidadSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 60, 80, 40));

        AceleracionLabel.setBackground(new java.awt.Color(241, 191, 217));
        AceleracionLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AceleracionLabel.setForeground(new java.awt.Color(190, 108, 157));
        AceleracionLabel.setText("Aceleracion (a):");
        getContentPane().add(AceleracionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        VelocidadFinalField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        VelocidadFinalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VelocidadFinalFieldActionPerformed(evt);
            }
        });
        getContentPane().add(VelocidadFinalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 290, 30));

        Respuesta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(Respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 240, 40));

        VelocidadFinalLabel1.setBackground(new java.awt.Color(241, 191, 217));
        VelocidadFinalLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        VelocidadFinalLabel1.setForeground(new java.awt.Color(190, 108, 157));
        VelocidadFinalLabel1.setText("Velocidad final (v):");
        getContentPane().add(VelocidadFinalLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        VelocidadInicialField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        VelocidadInicialField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VelocidadInicialFieldActionPerformed(evt);
            }
        });
        getContentPane().add(VelocidadInicialField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 260, 30));

        unidadVelocidadFinal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadVelocidadFinal.setForeground(new java.awt.Color(190, 108, 157));
        unidadVelocidadFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km/h", "m/s" }));
        unidadVelocidadFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadVelocidadFinalActionPerformed(evt);
            }
        });
        getContentPane().add(unidadVelocidadFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 110, 30));

        unidadAceleracion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadAceleracion.setForeground(new java.awt.Color(190, 108, 157));
        unidadAceleracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km/h²", "m/s²" }));
        unidadAceleracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadAceleracionActionPerformed(evt);
            }
        });
        getContentPane().add(unidadAceleracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 160, 30));

        unidadVelocidadInicial.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadVelocidadInicial.setForeground(new java.awt.Color(190, 108, 157));
        unidadVelocidadInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km/h", "m/s" }));
        unidadVelocidadInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadVelocidadInicialActionPerformed(evt);
            }
        });
        getContentPane().add(unidadVelocidadInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 110, 30));

        TiempoLabel1.setBackground(new java.awt.Color(241, 191, 217));
        TiempoLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TiempoLabel1.setForeground(new java.awt.Color(190, 108, 157));
        TiempoLabel1.setText("Tiempo (t):");
        getContentPane().add(TiempoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        tiempoField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tiempoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoFieldActionPerformed(evt);
            }
        });
        getContentPane().add(tiempoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 260, 30));

        unidadTiempo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadTiempo.setForeground(new java.awt.Color(190, 108, 157));
        unidadTiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "horas", "segundos" }));
        unidadTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadTiempoActionPerformed(evt);
            }
        });
        getContentPane().add(unidadTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 150, 30));

        formula.setBackground(new java.awt.Color(241, 191, 217));
        formula.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        formula.setForeground(new java.awt.Color(190, 108, 157));
        getContentPane().add(formula, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 510, 140));

        Limpiar.setBackground(new java.awt.Color(245, 215, 226));
        Limpiar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Limpiar.setForeground(new java.awt.Color(209, 129, 148));
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.dispose();
        SeleccionProblemas volver = new SeleccionProblemas();
        volver.setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    private void CalcularAceleracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularAceleracionActionPerformed
        try {
            // Verificar qué campos están presentes
            boolean tieneV = !VelocidadFinalField.getText().isEmpty();
            boolean tieneV0 = !VelocidadInicialField.getText().isEmpty();
            boolean tieneT = !tiempoField.getText().isEmpty();
            boolean tieneA = !AceleracionField.getText().isEmpty();

            // Parsear valores
            double v = tieneV ? Double.parseDouble(VelocidadFinalField.getText()) : 0;
            double v0 = tieneV0 ? Double.parseDouble(VelocidadInicialField.getText()) : 0;
            double t = tieneT ? Double.parseDouble(tiempoField.getText()) : 0;
            double a = tieneA ? Double.parseDouble(AceleracionField.getText()) : 0;

            // Convertir a unidades estándar
            if (tieneV && unidadVelocidadFinal.getSelectedItem().equals("km/h")) {
                v /= 3.6;
            }
            if (tieneV0 && unidadVelocidadInicial.getSelectedItem().equals("km/h")) {
                v0 /= 3.6;
            }
            if (tieneT && unidadTiempo.getSelectedItem().equals("horas")) {
                t *= 3600;
            }
            if (tieneA && unidadAceleracion.getSelectedItem().equals("km/h²")) {
                a /= 12960;
            }

            double d = 0;
            String formulaUsada = "";

            // Caso 1: d = v₀·t + ½·a·t²
            if (tieneV0 && tieneT && tieneA) {
                d = (v0 * t) + (0.5 * a * Math.pow(t, 2));
                formulaUsada = "d = v₀·t + ½·a·t²";
            } // Caso 2: d = (v² - v₀²) / (2·a)
            else if (tieneV && tieneV0 && tieneA && a != 0) {
                d = (Math.pow(v, 2) - Math.pow(v0, 2)) / (2 * a);
                formulaUsada = "d = (v² - v₀²) / (2·a)";
            } // Caso 3: d = v·t - ½·a·t²
            else if (tieneV && tieneT && tieneA) {
                d = (v * t) - (0.5 * a * Math.pow(t, 2));
                formulaUsada = "d = v·t - ½·a·t²";
            } else {
                JOptionPane.showMessageDialog(null, "Ingresa al menos 3 variables (excepto distancia).");
                return;
            }

            // Convertir a km si es necesario
            if (unidadSalida.getSelectedItem().equals("km")) {
                d /= 1000;
            }

            // Mostrar resultado
            Respuesta.setText(String.format("%.2f %s", d, unidadSalida.getSelectedItem().toString()));
            formula.setText(formulaUsada);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error: Ingresa solo números válidos.");
        }

    }//GEN-LAST:event_CalcularAceleracionActionPerformed

    private void AceleracionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceleracionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AceleracionFieldActionPerformed

    private void unidadSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadSalidaActionPerformed

    private void VelocidadFinalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VelocidadFinalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VelocidadFinalFieldActionPerformed

    private void VelocidadInicialFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VelocidadInicialFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VelocidadInicialFieldActionPerformed

    private void unidadVelocidadFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadVelocidadFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadVelocidadFinalActionPerformed

    private void unidadAceleracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadAceleracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadAceleracionActionPerformed

    private void unidadVelocidadInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadVelocidadInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadVelocidadInicialActionPerformed

    private void tiempoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoFieldActionPerformed

    private void unidadTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadTiempoActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // Limpiar todos los campos de texto

        VelocidadFinalField.setText("");
        tiempoField.setText("");
        VelocidadInicialField.setText("");
        AceleracionField.setText("");

        // Reiniciar los JComboBox a su primer elemento (opcional)
        unidadVelocidadFinal.setSelectedIndex(0);
        unidadVelocidadInicial.setSelectedIndex(0);
        unidadAceleracion.setSelectedIndex(0);
        unidadTiempo.setSelectedIndex(0);

        // Limpiar los resultados y fórmulas mostradas
        Respuesta.setText("");
        formula.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AceleracionField;
    private javax.swing.JLabel AceleracionLabel;
    private javax.swing.JButton CalcularAceleracion;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel Respuesta;
    private javax.swing.JLabel TiempoLabel;
    private javax.swing.JLabel TiempoLabel1;
    private javax.swing.JTextField VelocidadFinalField;
    private javax.swing.JLabel VelocidadFinalLabel1;
    private javax.swing.JTextField VelocidadInicialField;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel formula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tiempoField;
    private javax.swing.JComboBox<String> unidadAceleracion;
    private javax.swing.JComboBox<String> unidadSalida;
    private javax.swing.JComboBox<String> unidadTiempo;
    private javax.swing.JComboBox<String> unidadVelocidadFinal;
    private javax.swing.JComboBox<String> unidadVelocidadInicial;
    // End of variables declaration//GEN-END:variables
}
