/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofisica;

import javax.swing.JOptionPane;

/**
 *
 * @author gomez
 */
public class Tiempo extends javax.swing.JFrame {

    /**
     * Creates new form Tiempo
     */
    public Tiempo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        velocidadField = new javax.swing.JTextField();
        unidadVelocidad = new javax.swing.JComboBox<>();
        distanciaField = new javax.swing.JTextField();
        unidadSalida = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        unidadDistancia = new javax.swing.JComboBox<>();
        Masa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tiempoField = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(241, 191, 217));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(190, 108, 157));
        jLabel4.setText("Calcular tiempo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jLabel5.setBackground(new java.awt.Color(241, 191, 217));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(190, 108, 157));
        jLabel5.setText("Velocidad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        velocidadField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        velocidadField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velocidadFieldActionPerformed(evt);
            }
        });
        getContentPane().add(velocidadField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 256, -1));

        unidadVelocidad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadVelocidad.setForeground(new java.awt.Color(190, 108, 157));
        unidadVelocidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km/h", "m/s" }));
        unidadVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadVelocidadActionPerformed(evt);
            }
        });
        getContentPane().add(unidadVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 170, 40));

        distanciaField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        distanciaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanciaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(distanciaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 256, -1));

        unidadSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "horas", "segundos" }));
        unidadSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(unidadSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 87, 37));

        jLabel8.setBackground(new java.awt.Color(241, 191, 217));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(190, 108, 157));
        jLabel8.setText("Distancia");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jLabel6.setBackground(new java.awt.Color(241, 191, 217));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(190, 108, 157));
        jLabel6.setText("Respuesta en:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        unidadDistancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km", "m" }));
        unidadDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadDistanciaActionPerformed(evt);
            }
        });
        getContentPane().add(unidadDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 87, 37));

        Masa.setBackground(new java.awt.Color(241, 191, 217));
        Masa.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Masa.setForeground(new java.awt.Color(190, 108, 157));
        Masa.setText("calcular");
        Masa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasaActionPerformed(evt);
            }
        });
        getContentPane().add(Masa, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, 50));

        jLabel3.setBackground(new java.awt.Color(241, 191, 217));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(190, 108, 157));
        jLabel3.setText("Tiempo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));
        getContentPane().add(tiempoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 240, 40));

        jLabel1.setBackground(new java.awt.Color(241, 191, 217));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(190, 108, 157));
        jLabel1.setText("Formula:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, -1, -1));

        jLabel2.setBackground(new java.awt.Color(241, 191, 217));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(190, 108, 157));
        jLabel2.setText("t = v / d");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, -1, -1));

        Volver.setBackground(new java.awt.Color(245, 215, 226));
        Volver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Volver.setForeground(new java.awt.Color(209, 129, 148));
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 570, -1, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void velocidadFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velocidadFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_velocidadFieldActionPerformed

    private void unidadVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadVelocidadActionPerformed

    }//GEN-LAST:event_unidadVelocidadActionPerformed

    private void distanciaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanciaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distanciaFieldActionPerformed

    private void unidadSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadSalidaActionPerformed

    private void unidadDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadDistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadDistanciaActionPerformed

    private void MasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasaActionPerformed
    try {
        // Obtener velocidad y distancia de los campos de texto
        double velocidad = Double.parseDouble(velocidadField.getText());
        double distancia = Double.parseDouble(distanciaField.getText());

        // Convertir velocidad a km/h si es necesario
        if (unidadVelocidad.getSelectedItem().equals("m/s")) {
            velocidad *= 3.6; // Convertir m/s a km/h
        }

        // Convertir distancia a kilómetros si es necesario
        if (unidadDistancia.getSelectedItem().equals("m")) {
            distancia /= 1000; // Convertir metros a kilómetros
        }

        // Calcular tiempo
        if (velocidad > 0) {
            double tiempo = distancia / velocidad; // t = d / v

            // Mostrar resultados en la unidad seleccionada
            if (unidadSalida.getSelectedItem().equals("segundos")) {
                tiempo *= 3600; // Convertir horas a segundos
            }

            // Mostrar el resultado en el campo correspondiente
            tiempoField.setText(String.format("%.2f %s", tiempo, unidadSalida.getSelectedItem()));
        } else {
            JOptionPane.showMessageDialog(this, "La velocidad no puede ser cero.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa valores válidos.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_MasaActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.dispose();
        SeleccionProblemas volver = new SeleccionProblemas();
        volver.setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Masa;
    private javax.swing.JButton Volver;
    private javax.swing.JTextField distanciaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel tiempoField;
    private javax.swing.JComboBox<String> unidadDistancia;
    private javax.swing.JComboBox<String> unidadSalida;
    private javax.swing.JComboBox<String> unidadVelocidad;
    private javax.swing.JTextField velocidadField;
    // End of variables declaration//GEN-END:variables
}
