package com.mycompany.proyectofisica;

import javax.swing.JOptionPane;

/**
 *
 * @author gomez
 */
public class VelocidadInicial extends javax.swing.JFrame {

    /**
     * Creates new form VelocidadInicial
     */
    public VelocidadInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        formula = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        CalcularVelocidadInicial = new javax.swing.JButton();
        unidadSalida = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        distanciaLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tiempoField = new javax.swing.JTextField();
        unidadTiempo = new javax.swing.JComboBox<>();
        AceleracionLabel = new javax.swing.JLabel();
        AceleracionField = new javax.swing.JTextField();
        unidadAceleracion = new javax.swing.JComboBox<>();
        Respuesta = new javax.swing.JLabel();
        VelocidadFinalLabel1 = new javax.swing.JLabel();
        VelocidadFinalField = new javax.swing.JTextField();
        TiempoLabel = new javax.swing.JLabel();
        unidadDistancia = new javax.swing.JComboBox<>();
        distanciaField = new javax.swing.JTextField();
        unidadVelocidadFinal = new javax.swing.JComboBox<>();
        Limpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(241, 191, 217));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(190, 108, 157));
        jLabel1.setText("Formula:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        formula.setBackground(new java.awt.Color(241, 191, 217));
        formula.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        formula.setForeground(new java.awt.Color(190, 108, 157));
        getContentPane().add(formula, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 580, 200));

        Volver.setBackground(new java.awt.Color(245, 215, 226));
        Volver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Volver.setForeground(new java.awt.Color(209, 129, 148));
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 510, -1, -1));

        CalcularVelocidadInicial.setBackground(new java.awt.Color(241, 191, 217));
        CalcularVelocidadInicial.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        CalcularVelocidadInicial.setForeground(new java.awt.Color(190, 108, 157));
        CalcularVelocidadInicial.setText("calcular");
        CalcularVelocidadInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularVelocidadInicialActionPerformed(evt);
            }
        });
        getContentPane().add(CalcularVelocidadInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, -1, 50));

        unidadSalida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadSalida.setForeground(new java.awt.Color(190, 108, 157));
        unidadSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km/h", "m/s" }));
        unidadSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(unidadSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 130, 50));

        jLabel6.setBackground(new java.awt.Color(241, 191, 217));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(190, 108, 157));
        jLabel6.setText("Respuesta en:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, -1));

        distanciaLabel.setBackground(new java.awt.Color(241, 191, 217));
        distanciaLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        distanciaLabel.setForeground(new java.awt.Color(190, 108, 157));
        distanciaLabel.setText("distancia (x):");
        getContentPane().add(distanciaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel5.setBackground(new java.awt.Color(241, 191, 217));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(190, 108, 157));
        jLabel5.setText("Velocidad inicial (v₀):");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, -1, -1));

        jLabel4.setBackground(new java.awt.Color(241, 191, 217));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(190, 108, 157));
        jLabel4.setText("Calcular la velocidad inicial");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        tiempoField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tiempoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoFieldActionPerformed(evt);
            }
        });
        getContentPane().add(tiempoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 260, 30));

        unidadTiempo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        unidadTiempo.setForeground(new java.awt.Color(190, 108, 157));
        unidadTiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "horas", "segundos" }));
        unidadTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadTiempoActionPerformed(evt);
            }
        });
        getContentPane().add(unidadTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 150, 30));

        AceleracionLabel.setBackground(new java.awt.Color(241, 191, 217));
        AceleracionLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AceleracionLabel.setForeground(new java.awt.Color(190, 108, 157));
        AceleracionLabel.setText("Aceleracion (a):");
        getContentPane().add(AceleracionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        AceleracionField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AceleracionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceleracionFieldActionPerformed(evt);
            }
        });
        getContentPane().add(AceleracionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 290, 30));

        unidadAceleracion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadAceleracion.setForeground(new java.awt.Color(190, 108, 157));
        unidadAceleracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km/h²", "m/s²" }));
        unidadAceleracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadAceleracionActionPerformed(evt);
            }
        });
        getContentPane().add(unidadAceleracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 160, 30));

        Respuesta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(Respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 110, 330, 40));

        VelocidadFinalLabel1.setBackground(new java.awt.Color(241, 191, 217));
        VelocidadFinalLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        VelocidadFinalLabel1.setForeground(new java.awt.Color(190, 108, 157));
        VelocidadFinalLabel1.setText("Velocidad final (v):");
        getContentPane().add(VelocidadFinalLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        VelocidadFinalField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        VelocidadFinalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VelocidadFinalFieldActionPerformed(evt);
            }
        });
        getContentPane().add(VelocidadFinalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 260, 30));

        TiempoLabel.setBackground(new java.awt.Color(241, 191, 217));
        TiempoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TiempoLabel.setForeground(new java.awt.Color(190, 108, 157));
        TiempoLabel.setText("Tiempo (t):");
        getContentPane().add(TiempoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        unidadDistancia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadDistancia.setForeground(new java.awt.Color(190, 108, 157));
        unidadDistancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km", "mts" }));
        unidadDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadDistanciaActionPerformed(evt);
            }
        });
        getContentPane().add(unidadDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 110, 30));

        distanciaField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        distanciaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanciaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(distanciaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 260, 30));

        unidadVelocidadFinal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadVelocidadFinal.setForeground(new java.awt.Color(190, 108, 157));
        unidadVelocidadFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km/h", "m/s" }));
        unidadVelocidadFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadVelocidadFinalActionPerformed(evt);
            }
        });
        getContentPane().add(unidadVelocidadFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 110, 30));

        Limpiar.setBackground(new java.awt.Color(245, 215, 226));
        Limpiar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Limpiar.setForeground(new java.awt.Color(209, 129, 148));
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.dispose();
        SeleccionProblemas volver = new SeleccionProblemas();
        volver.setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    private void CalcularVelocidadInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularVelocidadInicialActionPerformed
        try {
            // Obtener valores de los campos (si no están vacíos)
            double vf = VelocidadFinalField.getText().isEmpty() ? 0 : Double.parseDouble(VelocidadFinalField.getText());
            double a = AceleracionField.getText().isEmpty() ? 0 : Double.parseDouble(AceleracionField.getText());
            double t = tiempoField.getText().isEmpty() ? 0 : Double.parseDouble(tiempoField.getText());
            double d = distanciaField.getText().isEmpty() ? 0 : Double.parseDouble(distanciaField.getText());

            // Convertir todas las unidades a estándar (m/s, segundos, metros)
            if (unidadVelocidadFinal.getSelectedItem().equals("km/h")) {
                vf /= 3.6;
            }
            if (unidadAceleracion.getSelectedItem().equals("km/h²")) {
                a /= 12960;
            } // Convertir km/h² a m/s²
            if (unidadTiempo.getSelectedItem().equals("horas")) {
                t *= 3600;
            }
            if (unidadDistancia.getSelectedItem().equals("km")) {
                d *= 1000;
            }

            double v0 = 0;
            
            double discriminante = Math.pow(vf, 2) - 2 * a * d;
            if (discriminante < 0) {
                JOptionPane.showMessageDialog(this, "❌ Error: No se puede calcular v₀ porque se obtiene una raíz negativa.");
                return;
            }
            v0 = Math.sqrt(discriminante);
            
            String formulaUsada = "";

            // Caso 1: Fórmula clásica (vf, a, t)
            if (a != 0 && t != 0) {
                v0 = vf - (a * t);
                formulaUsada = "v₀ = v - a·t";
            } // Caso 2: Usando distancia (vf, a, d)
            else if (a != 0 && d != 0) {
                v0 = Math.sqrt(Math.pow(vf, 2) - 2 * a * d);
                formulaUsada = "v₀ = √(v² - 2·a·d)";
            } // Caso 3: Si falta aceleración (vf, t, d)
            else if (t != 0 && d != 0) {
                a = (2 * (d - vf * t)) / Math.pow(t, 2);
                v0 = vf - (a * t);
                formulaUsada = "a = 2(d - v·t)/t² → v₀ = v - a·t";
            } else {
                JOptionPane.showMessageDialog(this, "⚠️ Ingresa al menos 3 variables (excepto v₀).");
                return;
            }

            // Convertir resultado a la unidad seleccionada
            if (unidadSalida.getSelectedItem().equals("km/h")) {
                v0 *= 3.6;
            }

            // Mostrar resultados
            Respuesta.setText(String.format("%.2f %s", v0, unidadSalida.getSelectedItem().toString()));
            formula.setText(formulaUsada);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "❌ Error: Ingresa solo números válidos.");
        }

    }//GEN-LAST:event_CalcularVelocidadInicialActionPerformed

    private void unidadSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadSalidaActionPerformed

    }//GEN-LAST:event_unidadSalidaActionPerformed

    private void tiempoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoFieldActionPerformed

    private void unidadTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadTiempoActionPerformed

    private void AceleracionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceleracionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AceleracionFieldActionPerformed

    private void unidadAceleracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadAceleracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadAceleracionActionPerformed

    private void unidadDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadDistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadDistanciaActionPerformed

    private void VelocidadFinalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VelocidadFinalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VelocidadFinalFieldActionPerformed

    private void distanciaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanciaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distanciaFieldActionPerformed

    private void unidadVelocidadFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadVelocidadFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadVelocidadFinalActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // Limpiar todos los campos de texto

        VelocidadFinalField.setText("");
        AceleracionField.setText("");
        tiempoField.setText("");
        distanciaField.setText("");

        // Reiniciar los JComboBox a su primer elemento (opcional)
        unidadVelocidadFinal.setSelectedIndex(0);
        unidadAceleracion.setSelectedIndex(0);
        unidadTiempo.setSelectedIndex(0);
        unidadDistancia.setSelectedIndex(0);

        // Limpiar los resultados y fórmulas mostradas
        Respuesta.setText("");

    }//GEN-LAST:event_LimpiarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AceleracionField;
    private javax.swing.JLabel AceleracionLabel;
    private javax.swing.JButton CalcularVelocidadInicial;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel Respuesta;
    private javax.swing.JLabel TiempoLabel;
    private javax.swing.JTextField VelocidadFinalField;
    private javax.swing.JLabel VelocidadFinalLabel1;
    private javax.swing.JButton Volver;
    private javax.swing.JTextField distanciaField;
    private javax.swing.JLabel distanciaLabel;
    private javax.swing.JLabel formula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tiempoField;
    private javax.swing.JComboBox<String> unidadAceleracion;
    private javax.swing.JComboBox<String> unidadDistancia;
    private javax.swing.JComboBox<String> unidadSalida;
    private javax.swing.JComboBox<String> unidadTiempo;
    private javax.swing.JComboBox<String> unidadVelocidadFinal;
    // End of variables declaration//GEN-END:variables
}
