package com.mycompany.proyectofisica;

import javax.swing.JOptionPane;

/**
 *
 * @author gomez
 */
public class VelocidadFinalMDP extends javax.swing.JFrame {

    /**
     * Creates new form VelocidadFinalMDP
     */
    public VelocidadFinalMDP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        Limpiar = new javax.swing.JButton();
        CalcularVelocidadInicial = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        formula = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Respuesta = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        VelocidadInicialField = new javax.swing.JTextField();
        unidadVelocidadInicial = new javax.swing.JComboBox<>();
        distanciaLabel1 = new javax.swing.JLabel();
        anguloField1 = new javax.swing.JTextField();
        unidadAngulo1 = new javax.swing.JComboBox<>();
        VelocidadFinalLabel1 = new javax.swing.JLabel();
        V0xField = new javax.swing.JTextField();
        unidadV0x = new javax.swing.JComboBox<>();
        unidadV0y = new javax.swing.JComboBox<>();
        V0yField = new javax.swing.JTextField();
        AceleracionLabel = new javax.swing.JLabel();
        unidadSalida = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        TtotalField = new javax.swing.JTextField();
        unidadTtotal = new javax.swing.JComboBox<>();
        unidady0 = new javax.swing.JComboBox<>();
        alturaInicialField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        hMaxField = new javax.swing.JTextField();
        unidadhMax = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        TiempoLabel = new javax.swing.JLabel();
        alturayField = new javax.swing.JTextField();
        unidadY = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(241, 191, 217));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(190, 108, 157));
        jLabel4.setText("Calcular la velocidad final");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        Limpiar.setBackground(new java.awt.Color(245, 215, 226));
        Limpiar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Limpiar.setForeground(new java.awt.Color(209, 129, 148));
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, -1, -1));

        CalcularVelocidadInicial.setBackground(new java.awt.Color(241, 191, 217));
        CalcularVelocidadInicial.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        CalcularVelocidadInicial.setForeground(new java.awt.Color(190, 108, 157));
        CalcularVelocidadInicial.setText("calcular");
        CalcularVelocidadInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularVelocidadInicialActionPerformed(evt);
            }
        });
        getContentPane().add(CalcularVelocidadInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, -1, 50));

        Volver.setBackground(new java.awt.Color(245, 215, 226));
        Volver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Volver.setForeground(new java.awt.Color(209, 129, 148));
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 510, -1, -1));

        jLabel1.setBackground(new java.awt.Color(241, 191, 217));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(190, 108, 157));
        jLabel1.setText("Formula:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        jLabel5.setBackground(new java.awt.Color(241, 191, 217));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(190, 108, 157));
        jLabel5.setText("Velocidad final:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        formula.setBackground(new java.awt.Color(241, 191, 217));
        formula.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        formula.setForeground(new java.awt.Color(190, 108, 157));
        getContentPane().add(formula, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 710, 190));

        jLabel6.setBackground(new java.awt.Color(241, 191, 217));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(190, 108, 157));
        jLabel6.setText("Respuesta en:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        Respuesta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(Respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 110, 350, 40));

        jLabel7.setBackground(new java.awt.Color(241, 191, 217));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(190, 108, 157));
        jLabel7.setText("Velocidad inicial (v₀):");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        VelocidadInicialField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        VelocidadInicialField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VelocidadInicialFieldActionPerformed(evt);
            }
        });
        getContentPane().add(VelocidadInicialField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 260, 30));

        unidadVelocidadInicial.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadVelocidadInicial.setForeground(new java.awt.Color(190, 108, 157));
        unidadVelocidadInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m/s", "km/h", " " }));
        unidadVelocidadInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadVelocidadInicialActionPerformed(evt);
            }
        });
        getContentPane().add(unidadVelocidadInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 110, 30));

        distanciaLabel1.setBackground(new java.awt.Color(241, 191, 217));
        distanciaLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        distanciaLabel1.setForeground(new java.awt.Color(190, 108, 157));
        distanciaLabel1.setText("Angulo (θ):");
        getContentPane().add(distanciaLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        anguloField1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        anguloField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anguloField1ActionPerformed(evt);
            }
        });
        getContentPane().add(anguloField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 260, 30));

        unidadAngulo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadAngulo1.setForeground(new java.awt.Color(190, 108, 157));
        unidadAngulo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°", "rad" }));
        unidadAngulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadAngulo1ActionPerformed(evt);
            }
        });
        getContentPane().add(unidadAngulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 90, 30));

        VelocidadFinalLabel1.setBackground(new java.awt.Color(241, 191, 217));
        VelocidadFinalLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        VelocidadFinalLabel1.setForeground(new java.awt.Color(190, 108, 157));
        VelocidadFinalLabel1.setText("V0x:");
        getContentPane().add(VelocidadFinalLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        V0xField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        V0xField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V0xFieldActionPerformed(evt);
            }
        });
        getContentPane().add(V0xField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 260, 30));

        unidadV0x.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadV0x.setForeground(new java.awt.Color(190, 108, 157));
        unidadV0x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m/s", "km/h}" }));
        unidadV0x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadV0xActionPerformed(evt);
            }
        });
        getContentPane().add(unidadV0x, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 110, 30));

        unidadV0y.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadV0y.setForeground(new java.awt.Color(190, 108, 157));
        unidadV0y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m/s", "km/h}" }));
        unidadV0y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadV0yActionPerformed(evt);
            }
        });
        getContentPane().add(unidadV0y, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 100, 30));

        V0yField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        V0yField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V0yFieldActionPerformed(evt);
            }
        });
        getContentPane().add(V0yField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 290, 30));

        AceleracionLabel.setBackground(new java.awt.Color(241, 191, 217));
        AceleracionLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AceleracionLabel.setForeground(new java.awt.Color(190, 108, 157));
        AceleracionLabel.setText("V0y:");
        getContentPane().add(AceleracionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        unidadSalida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadSalida.setForeground(new java.awt.Color(190, 108, 157));
        unidadSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m/s", "km/h" }));
        unidadSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(unidadSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 130, 50));

        jLabel9.setBackground(new java.awt.Color(241, 191, 217));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(190, 108, 157));
        jLabel9.setText("Ttotal:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 40));

        TtotalField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TtotalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtotalFieldActionPerformed(evt);
            }
        });
        getContentPane().add(TtotalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 260, 30));

        unidadTtotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadTtotal.setForeground(new java.awt.Color(190, 108, 157));
        unidadTtotal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "horas", "minutos", "segundos" }));
        unidadTtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadTtotalActionPerformed(evt);
            }
        });
        getContentPane().add(unidadTtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 150, 30));

        unidady0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidady0.setForeground(new java.awt.Color(190, 108, 157));
        unidady0.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m", "km" }));
        unidady0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidady0ActionPerformed(evt);
            }
        });
        getContentPane().add(unidady0, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 80, 30));

        alturaInicialField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        alturaInicialField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaInicialFieldActionPerformed(evt);
            }
        });
        getContentPane().add(alturaInicialField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 260, 30));

        jLabel10.setBackground(new java.awt.Color(241, 191, 217));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(190, 108, 157));
        jLabel10.setText("Altura inicial (y₀):");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 40));

        hMaxField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hMaxField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hMaxFieldActionPerformed(evt);
            }
        });
        getContentPane().add(hMaxField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 260, 30));

        unidadhMax.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadhMax.setForeground(new java.awt.Color(190, 108, 157));
        unidadhMax.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m", "km" }));
        unidadhMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadhMaxActionPerformed(evt);
            }
        });
        getContentPane().add(unidadhMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 80, 30));

        jLabel12.setBackground(new java.awt.Color(241, 191, 217));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(190, 108, 157));
        jLabel12.setText("Altura maxima (hmax):");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, 30));

        TiempoLabel.setBackground(new java.awt.Color(241, 191, 217));
        TiempoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TiempoLabel.setForeground(new java.awt.Color(190, 108, 157));
        TiempoLabel.setText("altura especifica (y):");
        getContentPane().add(TiempoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        alturayField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        alturayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturayFieldActionPerformed(evt);
            }
        });
        getContentPane().add(alturayField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 260, 30));

        unidadY.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadY.setForeground(new java.awt.Color(190, 108, 157));
        unidadY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m", "km" }));
        unidadY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadYActionPerformed(evt);
            }
        });
        getContentPane().add(unidadY, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        V0xField.setText("");
        V0yField.setText("");
        VelocidadInicialField.setText("");
        anguloField1.setText("");
        Respuesta.setText("");
        formula.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed
    private double calcularTiempoVuelo(double V0, double angulo, double y0) {
        double g = 9.81;
        double anguloRad = Math.toRadians(angulo);
        double V0y = V0 * Math.sin(anguloRad);

        double a = -0.5 * g;
        double b = V0y;
        double c = y0;

        double discriminante = b * b - 4 * a * c;
        if (discriminante < 0) {
            return -1;
        }

        double t1 = (-b + Math.sqrt(discriminante)) / (2 * a);
        double t2 = (-b - Math.sqrt(discriminante)) / (2 * a);

        if (t1 > 0 && t2 > 0) {
            return Math.max(t1, t2);
        } else if (t1 > 0) {
            return t1;
        } else if (t2 > 0) {
            return t2;
        } else {
            return -1;
        }
    }
    private void CalcularVelocidadInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularVelocidadInicialActionPerformed

    try {
        double g = 9.81;
        double V0 = VelocidadInicialField.getText().isEmpty() ? 0 : Double.parseDouble(VelocidadInicialField.getText());
        double angulo = anguloField1.getText().isEmpty() ? 0 : Double.parseDouble(anguloField1.getText());
        double anguloRad = Math.toRadians(angulo);
        double V0x = V0xField.getText().isEmpty() ? (V0 != 0 && angulo != 0 ? V0 * Math.cos(anguloRad) : 0) : Double.parseDouble(V0xField.getText());
        double V0y = V0yField.getText().isEmpty() ? (V0 != 0 && angulo != 0 ? V0 * Math.sin(anguloRad) : 0) : Double.parseDouble(V0yField.getText());
        double tiempoTotal = TtotalField.getText().isEmpty() ? 0 : Double.parseDouble(TtotalField.getText());
        double y0 = alturaInicialField.getText().isEmpty() ? 0 : Double.parseDouble(alturaInicialField.getText());
        double hMax = hMaxField.getText().isEmpty() ? 0 : Double.parseDouble(hMaxField.getText());
        double h = alturayField.getText().isEmpty() ? 0 : Double.parseDouble(alturayField.getText());

        double Vy = 0;
        double Vx = V0x != 0 ? V0x : (V0 * Math.cos(anguloRad));
        double Vfinal;
        double tiempoAlcanceVelocidadFinal = -1;
        String formulaUsada = "";

        // Caso 1: Con tiempo total
        if (tiempoTotal != 0) {
            Vy = V0y - g * tiempoTotal;
            tiempoAlcanceVelocidadFinal = tiempoTotal;
            formulaUsada = "Vy = V0y - g·t";
        }
        // Caso 2: En altura máxima
        else if (hMax != 0) {
            Vy = 0;
            tiempoAlcanceVelocidadFinal = V0y / g;
            formulaUsada = "Vy = 0 (en altura máxima)";
        }
        // Caso 3: En altura específica h
        else if (h != 0) {
            double a = -0.5 * g;
            double b = V0y;
            double c = y0 - h;

            double discriminante = b * b - 4 * a * c;
            if (discriminante < 0) {
                JOptionPane.showMessageDialog(this, "No hay solución real para esa altura.");
                return;
            }

            double t1 = (-b + Math.sqrt(discriminante)) / (2 * a);
            double t2 = (-b - Math.sqrt(discriminante)) / (2 * a);
            double tiempoAltura = (t1 > 0) ? t1 : t2;

            Vy = V0y - g * tiempoAltura;
            tiempoAlcanceVelocidadFinal = tiempoAltura;
            formulaUsada = String.format("Vy = V0y - g·t, con t=%.2f s (altura específica)", tiempoAltura);
        }
        // Caso 4: Vuelo parabólico desde el suelo
        else if (V0 != 0 && angulo != 0 && y0 == 0) {
            double t = (2 * V0y) / g;
            Vy = V0y - g * t;
            tiempoAlcanceVelocidadFinal = t;
            formulaUsada = String.format("Vy = V0·sen(θ) - g·t, con t=%.2f s (vuelta al suelo)", t);
        }      // Caso 5: Vuelo desde una altura y0 ≠ 0
else if (V0 != 0 && angulo != 0 && y0 != 0) {
    double t = calcularTiempoVuelo(V0, angulo, y0);
    if (t == -1) {
        JOptionPane.showMessageDialog(this, "El proyectil no llega al suelo.");
        return;
    }
    Vy = V0y - g * t;
    tiempoAlcanceVelocidadFinal = t;
    formulaUsada = String.format("Vy = V0·sen(θ) - g·t, con t=%.2f s (desde y0 ≠ 0)", t);
}
// Caso 7: Disparo completamente horizontal desde altura y0
else if (V0 != 0 && angulo == 0 && y0 != 0) {
    double t = Math.sqrt((2 * y0) / g);
    Vy = -g * t;
    tiempoAlcanceVelocidadFinal = t;
    formulaUsada = String.format("t = √(2·y₀/g) = %.2f s", t);
}
// Caso 6: Solo V0y disponible
else if (V0y != 0) {
    Vy = V0y;
    tiempoAlcanceVelocidadFinal = 0;
    formulaUsada = "Vy = V0y (sin tiempo)";
        } else {
            JOptionPane.showMessageDialog(this, "Ingresa suficientes datos para calcular velocidad final.");
            return;
        }

        // Calcular velocidad final (módulo)
        Vfinal = Math.sqrt(Vx * Vx + Vy * Vy);
        formulaUsada += " | V = √(Vx² + Vy²)";

        // Conversión si se solicita en km/h
        if (unidadSalida.getSelectedItem().equals("km/h")) {
            Vfinal *= 3.6;
        }

        // Mostrar resultado en el mismo JLabel
        if (tiempoAlcanceVelocidadFinal >= 0) {
            Respuesta.setText(String.format("V = %.2f %s | t = %.2f s", Vfinal, unidadSalida.getSelectedItem(), tiempoAlcanceVelocidadFinal));
        } else {
            Respuesta.setText(String.format("V = %.2f %s", Vfinal, unidadSalida.getSelectedItem()));
        }

        formula.setText(formulaUsada);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: Ingresa solo números válidos.");
    }
    }//GEN-LAST:event_CalcularVelocidadInicialActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.dispose();
        SeleccionProblemas volver = new SeleccionProblemas();
        volver.setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    private void VelocidadInicialFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VelocidadInicialFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VelocidadInicialFieldActionPerformed

    private void unidadVelocidadInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadVelocidadInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadVelocidadInicialActionPerformed

    private void anguloField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anguloField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anguloField1ActionPerformed

    private void unidadAngulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadAngulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadAngulo1ActionPerformed

    private void V0xFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V0xFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_V0xFieldActionPerformed

    private void unidadV0xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadV0xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadV0xActionPerformed

    private void unidadV0yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadV0yActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadV0yActionPerformed

    private void V0yFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V0yFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_V0yFieldActionPerformed

    private void unidadSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadSalidaActionPerformed

    }//GEN-LAST:event_unidadSalidaActionPerformed

    private void TtotalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtotalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TtotalFieldActionPerformed

    private void unidadTtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadTtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadTtotalActionPerformed

    private void unidady0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidady0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidady0ActionPerformed

    private void alturaInicialFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaInicialFieldActionPerformed

    }//GEN-LAST:event_alturaInicialFieldActionPerformed

    private void hMaxFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hMaxFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hMaxFieldActionPerformed

    private void unidadhMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadhMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadhMaxActionPerformed

    private void alturayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturayFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturayFieldActionPerformed

    private void unidadYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadYActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AceleracionLabel;
    private javax.swing.JButton CalcularVelocidadInicial;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel Respuesta;
    private javax.swing.JLabel TiempoLabel;
    private javax.swing.JTextField TtotalField;
    private javax.swing.JTextField V0xField;
    private javax.swing.JTextField V0yField;
    private javax.swing.JLabel VelocidadFinalLabel1;
    private javax.swing.JTextField VelocidadInicialField;
    private javax.swing.JButton Volver;
    private javax.swing.JTextField alturaInicialField;
    private javax.swing.JTextField alturayField;
    private javax.swing.JTextField anguloField1;
    private javax.swing.JLabel distanciaLabel1;
    private javax.swing.JLabel formula;
    private javax.swing.JTextField hMaxField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> unidadAngulo1;
    private javax.swing.JComboBox<String> unidadSalida;
    private javax.swing.JComboBox<String> unidadTtotal;
    private javax.swing.JComboBox<String> unidadV0x;
    private javax.swing.JComboBox<String> unidadV0y;
    private javax.swing.JComboBox<String> unidadVelocidadInicial;
    private javax.swing.JComboBox<String> unidadY;
    private javax.swing.JComboBox<String> unidadhMax;
    private javax.swing.JComboBox<String> unidady0;
    // End of variables declaration//GEN-END:variables
}
