package com.mycompany.proyectofisica;

import javax.swing.JOptionPane;

/**
 *
 * @author gomez
 */
public class VelocidadT extends javax.swing.JFrame {

    /**
     * Creates new form VelocidadT
     */
    public VelocidadT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        Limpiar = new javax.swing.JButton();
        CalcularVelocidadInicial = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        formula = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Respuesta = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        VelocidadInicialField = new javax.swing.JTextField();
        unidadVelocidadInicial = new javax.swing.JComboBox<>();
        distanciaLabel1 = new javax.swing.JLabel();
        anguloField1 = new javax.swing.JTextField();
        unidadAngulo1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        tiempoEnUnInstanteField = new javax.swing.JTextField();
        unidadTiempo = new javax.swing.JComboBox<>();
        VelocidadFinalLabel1 = new javax.swing.JLabel();
        V0xField = new javax.swing.JTextField();
        unidadV0x = new javax.swing.JComboBox<>();
        unidadV0y = new javax.swing.JComboBox<>();
        V0yField = new javax.swing.JTextField();
        AceleracionLabel = new javax.swing.JLabel();
        unidadSalida = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(241, 191, 217));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(190, 108, 157));
        jLabel4.setText("Calcular la velocidad instantanea");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        Limpiar.setBackground(new java.awt.Color(245, 215, 226));
        Limpiar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Limpiar.setForeground(new java.awt.Color(209, 129, 148));
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        CalcularVelocidadInicial.setBackground(new java.awt.Color(241, 191, 217));
        CalcularVelocidadInicial.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        CalcularVelocidadInicial.setForeground(new java.awt.Color(190, 108, 157));
        CalcularVelocidadInicial.setText("calcular");
        CalcularVelocidadInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularVelocidadInicialActionPerformed(evt);
            }
        });
        getContentPane().add(CalcularVelocidadInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, -1, 50));

        Volver.setBackground(new java.awt.Color(245, 215, 226));
        Volver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Volver.setForeground(new java.awt.Color(209, 129, 148));
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 510, -1, -1));

        jLabel1.setBackground(new java.awt.Color(241, 191, 217));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(190, 108, 157));
        jLabel1.setText("Formula:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        jLabel5.setBackground(new java.awt.Color(241, 191, 217));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(190, 108, 157));
        jLabel5.setText("Velocidad instantanea:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        formula.setBackground(new java.awt.Color(241, 191, 217));
        formula.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        formula.setForeground(new java.awt.Color(190, 108, 157));
        getContentPane().add(formula, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 580, 200));

        jLabel6.setBackground(new java.awt.Color(241, 191, 217));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(190, 108, 157));
        jLabel6.setText("Respuesta en:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        Respuesta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(Respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 110, 350, 40));

        jLabel7.setBackground(new java.awt.Color(241, 191, 217));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(190, 108, 157));
        jLabel7.setText("Velocidad inicial (v₀):");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        VelocidadInicialField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        VelocidadInicialField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VelocidadInicialFieldActionPerformed(evt);
            }
        });
        getContentPane().add(VelocidadInicialField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 260, 30));

        unidadVelocidadInicial.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadVelocidadInicial.setForeground(new java.awt.Color(190, 108, 157));
        unidadVelocidadInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m/s", "km/h", " " }));
        unidadVelocidadInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadVelocidadInicialActionPerformed(evt);
            }
        });
        getContentPane().add(unidadVelocidadInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 110, 30));

        distanciaLabel1.setBackground(new java.awt.Color(241, 191, 217));
        distanciaLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        distanciaLabel1.setForeground(new java.awt.Color(190, 108, 157));
        distanciaLabel1.setText("Angulo (θ):");
        getContentPane().add(distanciaLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        anguloField1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        anguloField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anguloField1ActionPerformed(evt);
            }
        });
        getContentPane().add(anguloField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 260, 30));

        unidadAngulo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadAngulo1.setForeground(new java.awt.Color(190, 108, 157));
        unidadAngulo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°", "rad" }));
        unidadAngulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadAngulo1ActionPerformed(evt);
            }
        });
        getContentPane().add(unidadAngulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 90, 30));

        jLabel8.setBackground(new java.awt.Color(241, 191, 217));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(190, 108, 157));
        jLabel8.setText("T':");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 40));

        tiempoEnUnInstanteField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tiempoEnUnInstanteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoEnUnInstanteFieldActionPerformed(evt);
            }
        });
        getContentPane().add(tiempoEnUnInstanteField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 350, 30));

        unidadTiempo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadTiempo.setForeground(new java.awt.Color(190, 108, 157));
        unidadTiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "horas", "minutos", "segundos" }));
        unidadTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadTiempoActionPerformed(evt);
            }
        });
        getContentPane().add(unidadTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 150, 30));

        VelocidadFinalLabel1.setBackground(new java.awt.Color(241, 191, 217));
        VelocidadFinalLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        VelocidadFinalLabel1.setForeground(new java.awt.Color(190, 108, 157));
        VelocidadFinalLabel1.setText("V0x:");
        getContentPane().add(VelocidadFinalLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        V0xField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        V0xField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V0xFieldActionPerformed(evt);
            }
        });
        getContentPane().add(V0xField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 260, 30));

        unidadV0x.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadV0x.setForeground(new java.awt.Color(190, 108, 157));
        unidadV0x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m/s", "km/h}" }));
        unidadV0x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadV0xActionPerformed(evt);
            }
        });
        getContentPane().add(unidadV0x, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 110, 30));

        unidadV0y.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadV0y.setForeground(new java.awt.Color(190, 108, 157));
        unidadV0y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m/s", "km/h}" }));
        unidadV0y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadV0yActionPerformed(evt);
            }
        });
        getContentPane().add(unidadV0y, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 100, 30));

        V0yField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        V0yField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V0yFieldActionPerformed(evt);
            }
        });
        getContentPane().add(V0yField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 290, 30));

        AceleracionLabel.setBackground(new java.awt.Color(241, 191, 217));
        AceleracionLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AceleracionLabel.setForeground(new java.awt.Color(190, 108, 157));
        AceleracionLabel.setText("V0y:");
        getContentPane().add(AceleracionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        unidadSalida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadSalida.setForeground(new java.awt.Color(190, 108, 157));
        unidadSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m/s", "km/h" }));
        unidadSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(unidadSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 130, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        V0xField.setText("");
        V0yField.setText("");
        VelocidadInicialField.setText("");
        anguloField1.setText("");
        tiempoEnUnInstanteField.setText("");;
        Respuesta.setText("");
        formula.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void CalcularVelocidadInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularVelocidadInicialActionPerformed
try {
    double g = 9.81;
    double velocidad = 0;
    String formulaUsada = "";

     double V0 = VelocidadInicialField.getText().isEmpty() ? 0 : Double.parseDouble(VelocidadInicialField.getText());
            double angulo = anguloField1.getText().isEmpty() ? 0 : Double.parseDouble(anguloField1.getText());
            double anguloRad = Math.toRadians(angulo);
            double V0x = V0xField.getText().isEmpty() ? 0 : Double.parseDouble(V0xField.getText());
            double V0y = V0yField.getText().isEmpty() ? 0 : Double.parseDouble(V0yField.getText());
            double tiempo = tiempoEnUnInstanteField.getText().isEmpty() ? 0 : Double.parseDouble(tiempoEnUnInstanteField.getText());
// CONVERSIÓN DE UNIDADES A SISTEMA INTERNACIONAL

// Velocidad inicial V0
if (unidadVelocidadInicial.getSelectedItem().equals("km/h")) {
    V0 /= 3.6;
}

// Velocidad inicial en X
if (unidadV0x.getSelectedItem().equals("km/h")) {
    V0x /= 3.6;
}

// Velocidad inicial en Y
if (unidadV0y.getSelectedItem().equals("km/h")) {
    V0y /= 3.6;
}

// Ángulo
if (unidadAngulo1.getSelectedItem().equals("rad")) {
    anguloRad = angulo; // ya está en radianes
} else {
    anguloRad = Math.toRadians(angulo); // convertir de grados a radianes
}

// Tiempo
if (unidadTiempo.getSelectedItem().equals("min")) {
    tiempo *= 60; // minutos a segundos
} else if (unidadTiempo.getSelectedItem().equals("h")) {
    tiempo *= 3600; // horas a segundos
}
// si ya está en segundos, no se hace nada
    // Calcular V0x y V0y si no se proporcionan
    if (V0 != 0 && angulo != 0) {
        V0x = V0 * Math.cos(anguloRad);
        V0y = V0 * Math.sin(anguloRad);
    }

    if (V0x != 0 && V0y != 0 && tiempo != 0) {
        double Vx = V0x; // constante
        double Vy = V0y - g * tiempo;
        velocidad = Math.sqrt(Vx * Vx + Vy * Vy);
        formulaUsada = "v = √(V₀x² + (V₀y - g·t)²)";
    } else {
        JOptionPane.showMessageDialog(this, "Ingresa una combinación válida de datos.");
        return;
    }
if (unidadSalida.getSelectedItem().equals("km/h")) {
    velocidad *= 3.6;
}
    Respuesta.setText(String.format("%.2f " + unidadSalida.getSelectedItem(), velocidad));
    formula.setText(formulaUsada);

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Error: Ingresa solo números válidos.");
}
    }//GEN-LAST:event_CalcularVelocidadInicialActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.dispose();
        SeleccionProblemas volver = new SeleccionProblemas();
        volver.setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    private void VelocidadInicialFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VelocidadInicialFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VelocidadInicialFieldActionPerformed

    private void unidadVelocidadInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadVelocidadInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadVelocidadInicialActionPerformed

    private void anguloField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anguloField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anguloField1ActionPerformed

    private void unidadAngulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadAngulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadAngulo1ActionPerformed

    private void tiempoEnUnInstanteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoEnUnInstanteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoEnUnInstanteFieldActionPerformed

    private void unidadTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadTiempoActionPerformed

    private void V0xFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V0xFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_V0xFieldActionPerformed

    private void unidadV0xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadV0xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadV0xActionPerformed

    private void unidadV0yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadV0yActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadV0yActionPerformed

    private void V0yFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V0yFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_V0yFieldActionPerformed

    private void unidadSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadSalidaActionPerformed

    }//GEN-LAST:event_unidadSalidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AceleracionLabel;
    private javax.swing.JButton CalcularVelocidadInicial;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel Respuesta;
    private javax.swing.JTextField V0xField;
    private javax.swing.JTextField V0yField;
    private javax.swing.JLabel VelocidadFinalLabel1;
    private javax.swing.JTextField VelocidadInicialField;
    private javax.swing.JButton Volver;
    private javax.swing.JTextField anguloField1;
    private javax.swing.JLabel distanciaLabel1;
    private javax.swing.JLabel formula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tiempoEnUnInstanteField;
    private javax.swing.JComboBox<String> unidadAngulo1;
    private javax.swing.JComboBox<String> unidadSalida;
    private javax.swing.JComboBox<String> unidadTiempo;
    private javax.swing.JComboBox<String> unidadV0x;
    private javax.swing.JComboBox<String> unidadV0y;
    private javax.swing.JComboBox<String> unidadVelocidadInicial;
    // End of variables declaration//GEN-END:variables
}
