package com.mycompany.proyectofisica;

import javax.swing.JOptionPane;

public class VelocidadInicialMDP extends javax.swing.JFrame {

    public VelocidadInicialMDP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        VelocidadFinalLabel1 = new javax.swing.JLabel();
        V0xField = new javax.swing.JTextField();
        unidadV0y = new javax.swing.JComboBox<>();
        V0yField = new javax.swing.JTextField();
        AceleracionLabel = new javax.swing.JLabel();
        TiempoLabel = new javax.swing.JLabel();
        distanciaLabel = new javax.swing.JLabel();
        AlcanceField = new javax.swing.JTextField();
        anguloField = new javax.swing.JTextField();
        unidadAlcance = new javax.swing.JComboBox<>();
        Limpiar = new javax.swing.JButton();
        CalcularVelocidadInicial = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        formula = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Respuesta = new javax.swing.JLabel();
        unidadSalida = new javax.swing.JComboBox<>();
        unidadV0x = new javax.swing.JComboBox<>();
        unidadAngulo = new javax.swing.JComboBox<>();
        hMaxField = new javax.swing.JTextField();
        unidadhMax = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TtotalField = new javax.swing.JTextField();
        unidadTtotal = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(241, 191, 217));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(190, 108, 157));
        jLabel4.setText("Calcular la velocidad inicial");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        VelocidadFinalLabel1.setBackground(new java.awt.Color(241, 191, 217));
        VelocidadFinalLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        VelocidadFinalLabel1.setForeground(new java.awt.Color(190, 108, 157));
        VelocidadFinalLabel1.setText("V0x:");
        getContentPane().add(VelocidadFinalLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        V0xField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        V0xField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V0xFieldActionPerformed(evt);
            }
        });
        getContentPane().add(V0xField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 260, 30));

        unidadV0y.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadV0y.setForeground(new java.awt.Color(190, 108, 157));
        unidadV0y.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m/s", "km/h}" }));
        unidadV0y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadV0yActionPerformed(evt);
            }
        });
        getContentPane().add(unidadV0y, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 100, 30));

        V0yField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        V0yField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V0yFieldActionPerformed(evt);
            }
        });
        getContentPane().add(V0yField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 290, 30));

        AceleracionLabel.setBackground(new java.awt.Color(241, 191, 217));
        AceleracionLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AceleracionLabel.setForeground(new java.awt.Color(190, 108, 157));
        AceleracionLabel.setText("V0y:");
        getContentPane().add(AceleracionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        TiempoLabel.setBackground(new java.awt.Color(241, 191, 217));
        TiempoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TiempoLabel.setForeground(new java.awt.Color(190, 108, 157));
        TiempoLabel.setText("Alcance (R):");
        getContentPane().add(TiempoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        distanciaLabel.setBackground(new java.awt.Color(241, 191, 217));
        distanciaLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        distanciaLabel.setForeground(new java.awt.Color(190, 108, 157));
        distanciaLabel.setText("Angulo (θ):");
        getContentPane().add(distanciaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        AlcanceField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AlcanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlcanceFieldActionPerformed(evt);
            }
        });
        getContentPane().add(AlcanceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 260, 30));

        anguloField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        anguloField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anguloFieldActionPerformed(evt);
            }
        });
        getContentPane().add(anguloField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 260, 30));

        unidadAlcance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadAlcance.setForeground(new java.awt.Color(190, 108, 157));
        unidadAlcance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km", "mts" }));
        unidadAlcance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadAlcanceActionPerformed(evt);
            }
        });
        getContentPane().add(unidadAlcance, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 110, 30));

        Limpiar.setBackground(new java.awt.Color(245, 215, 226));
        Limpiar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Limpiar.setForeground(new java.awt.Color(209, 129, 148));
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        CalcularVelocidadInicial.setBackground(new java.awt.Color(241, 191, 217));
        CalcularVelocidadInicial.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        CalcularVelocidadInicial.setForeground(new java.awt.Color(190, 108, 157));
        CalcularVelocidadInicial.setText("calcular");
        CalcularVelocidadInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularVelocidadInicialActionPerformed(evt);
            }
        });
        getContentPane().add(CalcularVelocidadInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, -1, 50));

        Volver.setBackground(new java.awt.Color(245, 215, 226));
        Volver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Volver.setForeground(new java.awt.Color(209, 129, 148));
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 510, -1, -1));

        jLabel1.setBackground(new java.awt.Color(241, 191, 217));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(190, 108, 157));
        jLabel1.setText("Formula:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        jLabel5.setBackground(new java.awt.Color(241, 191, 217));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(190, 108, 157));
        jLabel5.setText("Velocidad inicial (v₀):");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, -1));

        formula.setBackground(new java.awt.Color(241, 191, 217));
        formula.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        formula.setForeground(new java.awt.Color(190, 108, 157));
        getContentPane().add(formula, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 580, 200));

        jLabel6.setBackground(new java.awt.Color(241, 191, 217));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(190, 108, 157));
        jLabel6.setText("Respuesta en:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        Respuesta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(Respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 100, 330, 40));

        unidadSalida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadSalida.setForeground(new java.awt.Color(190, 108, 157));
        unidadSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "km/h", "m/s" }));
        unidadSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(unidadSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 130, 50));

        unidadV0x.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadV0x.setForeground(new java.awt.Color(190, 108, 157));
        unidadV0x.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m/s", "km/h}" }));
        unidadV0x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadV0xActionPerformed(evt);
            }
        });
        getContentPane().add(unidadV0x, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 110, 30));

        unidadAngulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadAngulo.setForeground(new java.awt.Color(190, 108, 157));
        unidadAngulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°", "rad" }));
        unidadAngulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadAnguloActionPerformed(evt);
            }
        });
        getContentPane().add(unidadAngulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 90, 30));

        hMaxField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hMaxField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hMaxFieldActionPerformed(evt);
            }
        });
        getContentPane().add(hMaxField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 260, 30));

        unidadhMax.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadhMax.setForeground(new java.awt.Color(190, 108, 157));
        unidadhMax.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "m", "km" }));
        unidadhMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadhMaxActionPerformed(evt);
            }
        });
        getContentPane().add(unidadhMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 80, 30));

        jLabel12.setBackground(new java.awt.Color(241, 191, 217));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(190, 108, 157));
        jLabel12.setText("Altura maxima (hmax):");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, 40));

        jLabel9.setBackground(new java.awt.Color(241, 191, 217));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(190, 108, 157));
        jLabel9.setText("Ttotal:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, 40));

        TtotalField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TtotalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtotalFieldActionPerformed(evt);
            }
        });
        getContentPane().add(TtotalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 260, 30));

        unidadTtotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        unidadTtotal.setForeground(new java.awt.Color(190, 108, 157));
        unidadTtotal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "horas", "minutos", "segundos" }));
        unidadTtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadTtotalActionPerformed(evt);
            }
        });
        getContentPane().add(unidadTtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void V0xFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V0xFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_V0xFieldActionPerformed

    private void unidadV0yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadV0yActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadV0yActionPerformed

    private void V0yFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V0yFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_V0yFieldActionPerformed

    private void AlcanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlcanceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlcanceFieldActionPerformed

    private void anguloFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anguloFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anguloFieldActionPerformed

    private void unidadAlcanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadAlcanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadAlcanceActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        V0xField.setText("");
        V0yField.setText("");
        AlcanceField.setText("");
        anguloField.setText("");
        hMaxField.setText("");
        TtotalField.setText("");
        Respuesta.setText("");
        formula.setText("");

    }//GEN-LAST:event_LimpiarActionPerformed

    private void CalcularVelocidadInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularVelocidadInicialActionPerformed
        try {
            // Obtener valores ingresados (en sus unidades originales)
            double V0x = V0xField.getText().isEmpty() ? 0 : Double.parseDouble(V0xField.getText());
            double V0y = V0yField.getText().isEmpty() ? 0 : Double.parseDouble(V0yField.getText());
            double alcance = AlcanceField.getText().isEmpty() ? 0 : Double.parseDouble(AlcanceField.getText());
            double anguloDeg = anguloField.getText().isEmpty() ? 0 : Double.parseDouble(anguloField.getText());
            double hmax = hMaxField.getText().isEmpty() ? 0 : Double.parseDouble(hMaxField.getText());
            double tiempo = TtotalField.getText().isEmpty() ? 0 : Double.parseDouble(TtotalField.getText());

            // Convertir unidades a estándar (m/s, m, s, °)
            if (unidadV0x.getSelectedItem().equals("km/h")) {
                V0x /= 3.6;
            }
            if (unidadV0y.getSelectedItem().equals("km/h")) {
                V0y /= 3.6;
            }
            if (unidadAlcance.getSelectedItem().equals("km")) {
                alcance *= 1000;
            }
            if (unidadhMax.getSelectedItem().equals("km")) {
                hmax *= 1000;
            }
            if (unidadTtotal.getSelectedItem().equals("horas")) {
                tiempo *= 3600;
            }
            if (unidadTtotal.getSelectedItem().equals("minutos")) {
                tiempo *= 60;
            }
            double anguloRad = Math.toRadians(anguloDeg);
            if (unidadAngulo.getSelectedItem().equals("rad")) {
                anguloRad = anguloDeg; // ya está en radianes
            } else {
                anguloRad = Math.toRadians(anguloDeg); // convertir de grados a radianes
            }

            double g = 9.81;
            double V0 = 0;
            String formulaUsada = "";

            // Cálculos con combinaciones posibles
            if (V0x != 0 && V0y != 0) {
                V0 = Math.sqrt(V0x * V0x + V0y * V0y);
                formulaUsada = "V₀ = √(V₀x² + V₀y²)";
            } else if (alcance != 0 && tiempo != 0 && anguloRad != 0) {
                V0 = alcance / (Math.cos(anguloRad) * tiempo);
                formulaUsada = "V₀ = R / (cos(θ)·t)";
            } else if (alcance != 0 && anguloRad != 0 && tiempo != 0) {
                double Vx = alcance / tiempo;
                double Vy = (g * tiempo) / 2;
                V0 = Math.sqrt(Vx * Vx + Vy * Vy);
                formulaUsada = "V₀ = √[(alcance/t)² + (g·t/2)²]";
            } else if (hmax != 0 && anguloRad != 0) {
                double Vy = Math.sqrt(2 * g * hmax);
                V0 = Vy / Math.sin(anguloRad);
                formulaUsada = "V₀ = √(2·g·hₘₐₓ) / sen(θ)";
            } else if (alcance != 0 && anguloRad != 0) {
                double sen2θ = Math.sin(2 * anguloRad);
                if (sen2θ == 0) {
                    JOptionPane.showMessageDialog(this, "Error: El ángulo no permite calcular alcance (sen(2θ) = 0).");
                    return;
                }
                V0 = Math.sqrt((alcance * g) / sen2θ);
                formulaUsada = "V₀ = √[(R·g) / sen(2θ)]";
            } else if (hmax != 0 && tiempo != 0) {
                double Vy = g * tiempo / 2;
                double Vx = alcance / tiempo;
                V0 = Math.sqrt(Vx * Vx + Vy * Vy);
                formulaUsada = "V₀ = √[(R/t)² + (g·t/2)²]";
            } else if (tiempo != 0 && anguloRad != 0) {
                V0 = (g * tiempo) / (2 * Math.sin(anguloRad));
                formulaUsada = "V₀ = (g·t) / (2·sen(θ))";
            } else if (alcance != 0 && tiempo != 0 && anguloRad != 0) {
                double Vx = alcance / tiempo;
                V0 = Vx / Math.cos(anguloRad);
                formulaUsada = "V₀ = (R / t) / cos(θ)";
            } else {
                JOptionPane.showMessageDialog(this, "Ingresa una combinación válida de datos para calcular V₀.");
                return;
            }

            // Convertir unidad de salida si es km/h
            if (unidadSalida.getSelectedItem().equals("km/h")) {
                V0 *= 3.6;
            }

            // Mostrar resultado
            Respuesta.setText(String.format("%.2f %s", V0, unidadSalida.getSelectedItem()));
            formula.setText(formulaUsada);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Ingresa solo números válidos.");
        }
    }//GEN-LAST:event_CalcularVelocidadInicialActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.dispose();
        SeleccionProblemas volver = new SeleccionProblemas();
        volver.setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    private void unidadSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadSalidaActionPerformed

    }//GEN-LAST:event_unidadSalidaActionPerformed

    private void unidadV0xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadV0xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadV0xActionPerformed

    private void unidadAnguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadAnguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadAnguloActionPerformed

    private void hMaxFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hMaxFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hMaxFieldActionPerformed

    private void unidadhMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadhMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadhMaxActionPerformed

    private void TtotalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtotalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TtotalFieldActionPerformed

    private void unidadTtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadTtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadTtotalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AceleracionLabel;
    private javax.swing.JTextField AlcanceField;
    private javax.swing.JButton CalcularVelocidadInicial;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel Respuesta;
    private javax.swing.JLabel TiempoLabel;
    private javax.swing.JTextField TtotalField;
    private javax.swing.JTextField V0xField;
    private javax.swing.JTextField V0yField;
    private javax.swing.JLabel VelocidadFinalLabel1;
    private javax.swing.JButton Volver;
    private javax.swing.JTextField anguloField;
    private javax.swing.JLabel distanciaLabel;
    private javax.swing.JLabel formula;
    private javax.swing.JTextField hMaxField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> unidadAlcance;
    private javax.swing.JComboBox<String> unidadAngulo;
    private javax.swing.JComboBox<String> unidadSalida;
    private javax.swing.JComboBox<String> unidadTtotal;
    private javax.swing.JComboBox<String> unidadV0x;
    private javax.swing.JComboBox<String> unidadV0y;
    private javax.swing.JComboBox<String> unidadhMax;
    // End of variables declaration//GEN-END:variables
}
